apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-api
  namespace: ott
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ott-api
  template:
    metadata:
      labels:
        app: ott-api
    spec:
      serviceAccountName: ott-api
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: api
          image: yny.ocir.io/axvqyylkrvmi/ott-api:6e89a1256188ae170d068540561b0008495df602
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "6e89a12"
            - name: TELEGRAM_NOTIFY_ENABLED
              value: "true"
            - name: TELEGRAM_SERVICE_NAME
              value: "ottline"
            - name: CURATOR_AUTOMATION_ENABLED
              value: "true"
            - name: CURATOR_TELEGRAM_APPROVER_USER_ID
              valueFrom:
                secretKeyRef:
                  name: ott-api-secrets
                  key: TELEGRAM_CHAT_ID
            - name: CF_REQUEST_HOST
              value: "ottline.app"
          envFrom:
            - secretRef:
                name: ott-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ott-api
  namespace: ott
spec:
  selector:
    app: ott-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
