apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-web
  namespace: ott
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ott-web
  template:
    metadata:
      labels:
        app: ott-web
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: web
          image: yny.ocir.io/axvqyylkrvmi/ott-web:ec08179a229bc0e8b23df31d31e639651338d7f0
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "ec08179"
          envFrom:
            - configMapRef:
                name: ott-web-config
            - secretRef:
                name: ott-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ott-web
  namespace: ott
spec:
  selector:
    app: ott-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
