apiVersion: apps/v1
kind: Deployment
metadata:
  name: ott-web
  namespace: ott
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ott-web
  template:
    metadata:
      labels:
        app: ott-web
    spec:
      imagePullSecrets:
        - name: ocir-pull-secret
      containers:
        - name: web
          image: yny.ocir.io/axvqyylkrvmi/ott-web:1da056e8a10411d1eccc4f4728a33f64344a9420
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "1da056e"
          envFrom:
            - configMapRef:
                name: ott-web-config
            - secretRef:
                name: ott-web-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: ott-web
  namespace: ott
spec:
  selector:
    app: ott-web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
